trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "16.18.0"
    displayName: "Install Node.js"

  - script: |
      yarn install
    displayName: "yarn install"

  - script: |
      yarn lint
    displayName: "lint"

  - script: |
      yarn build
    displayName: "compile"

  - script: |
      yarn test
    displayName: "test"

  - publish: "$(System.DefaultWorkingDirectory)/dist"
    artifact: "dist"
